stages:
- stage: CodeFormatting
  jobs:
  - job: CodeFormatting
    pool:
      vmImage: Ubuntu-24.04

    steps:
    - script: |
        clang-format --version
        find . -iname "*.hpp" -o -iname "*.cpp" | xargs clang-format -i
        git diff --exit-code $(Build.SourceVersion)
      failOnStderr: true
      displayName: 'Check code formatting'

- stage: Build
  condition: succeeded('CodeFormatting')
  jobs:
  - job: Build
    strategy:
      matrix:
        Windows_vc145_Debug:
          vmImage: windows-2025-vs2026
          configuration: Debug
          folder: 18
          opts: '-G "Visual Studio 18 2026" -T v145 -A x64'
        Windows_vc145_Release:
          vmImage: windows-2025-vs2026
          configuration: Release
          folder: 18
          opts: '-G "Visual Studio 18 2026" -T v145 -A x64'
        Windows_vc143_Debug:
          vmImage: windows-2025
          configuration: Debug
          folder: 2022
          opts: '-G Ninja -DCMAKE_BUILD_TYPE=$(configuration)'
        Windows_vc143_Release:
          vmImage: windows-2025
          configuration: Release
          folder: 2022
          opts: '-G Ninja -DCMAKE_BUILD_TYPE=$(configuration)'

    pool:
      vmImage: $(vmImage)

    steps:
      - checkout: self
        fetchDepth: 1

      - bash: |
          choco install ninja
        displayName: 'Install'

      - bash: |
          git config --global user.email "dummy@example.com"
          git config --global user.name "Dummy Name"
        displayName: 'Config git'

      - task: Cache@2
        inputs:
          key: 'Build | azure-pipelines.yml | External/**/CMakeLists.txt, !External/*/*/** | $(Agent.JobName)'
          restoreKeys: 'Build | $(Agent.JobName)'
          path: Build
        displayName: Cache Build

      - task: Cache@2
        inputs:
          key: 'External | azure-pipelines.yml | External/**/CMakeLists.txt, !External/*/*/** | $(Agent.JobName)'
          restoreKeys: 'External | $(Agent.JobName)'
          path: External
        displayName: Cache External

      - script: |
          call "C:\Program Files\Microsoft Visual Studio\$(folder)\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          cmake -B Build $(opts) . -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl -DCMAKE_LINKER=link
          cmake --build Build --config $(configuration) -j
        displayName: 'Build'

      - bash: |
          rm -rf Build/bin
          rm -rf Build/Source
        displayName: 'Remove uncached files'
